export const ITEM_ADDED = 'ITEM_ADDED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const ITEM_CHANGES_SAVED = 'ITEM_CHANGES_SAVED';
export const ITEM_EDITING_MODE_CHANGED = 'ITEM_EDITING_MODE_CHANGED';
export const ITEMS_REQUESTED = 'ITEMS_REQUESTED';
export const ITEMS_RECEIVED = 'ITEMS_RECEIVED';
