export const ITEM_ADD_STARTED = 'ITEM_ADD_STARTED';
export const ITEM_ADD_SUCCEEDED = 'ITEM_ADD_SUCCEEDED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const ITEM_CHANGES_SAVED = 'ITEM_CHANGES_SAVED';
export const ITEM_EDITING_MODE_CHANGED = 'ITEM_EDITING_MODE_CHANGED';
export const ITEMS_FETCH_STARTED = 'ITEMS_FETCH_STARTED';
export const ITEMS_FETCH_SUCCEEDED = 'ITEMS_FETCH_SUCCEEDED';
export const ITEMS_FETCH_FAILED = 'ITEMS_FETCH_FAILED';
